const path = require('path');
require('dotenv').config({ path: `env/.env`});

module.exports = {
  publicRuntimeConfig: {
    REACT_APP_FIREBASE_APIKEY: process.env.REACT_APP_FIREBASE_APIKEY,
    REACT_APP_FIREBASE_APPID:  process.env.REACT_APP_FIREBASE_APPID,
    REACT_APP_FIREBASE_AUTHDOMAIN:  process.env.REACT_APP_FIREBASE_AUTHDOMAIN,
    REACT_APP_FIREBASE_DATABASEURL:  process.env.REACT_APP_FIREBASE_DATABASEURL,
    REACT_APP_FIREBASE_MESSAGESENDERID:  process.env.REACT_APP_FIREBASE_MESSAGESENDERID,
    REACT_APP_FIREBASE_PROJECTID:  process.env.REACT_APP_FIREBASE_PROJECTID,
    REACT_APP_GRAPHQL_URL:  process.env.REACT_APP_GRAPHQL_URL,
    REACT_APP_TASK_URL:  process.env.REACT_APP_TASK_URL,
    BASE_PATH: '/'
  },
};